name: stackpipeline4
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - geowombat=2.1.8
  - rasterio=1.3.4
  - tk=8.6.12
  - pandas=2.0.2
  - laspy=2.4.1
  - numpy=1.25.0
  - scipy=1.11.0
  - spyder=5.4.3
  - xarray=2023.6.0
  - python-pdal=3.2.3
  - pip:
      - customtkinter==5.2.0
      

